events { 
    worker_connections 1024; 
}

http {
    # Khai báo cụm server phía sau (Upstream)
    upstream flash_food_api {
        # Thuật toán mặc định là Round-Robin (chia đều xoay vòng)
        server api_node_1:8080;
        server api_node_2:8080;
        server api_node_3:8080;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://flash_food_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Tính năng Failover: Tự động chuyển request sang node khác 
            # nếu node hiện tại bị sập (lỗi 500) hoặc phản hồi quá chậm (timeout)
            proxy_next_upstream error timeout http_500;
            proxy_connect_timeout 2s;
        }
    }
}